docs: add wmebv rapport
nl-design-system/gebruikersonderzoeken pull request #125
Opened 2024-01-22 18:44 UTC by Yolijn

2024-01-25 21:32 UTC, JeroenduC commented
Enige wat ik kon vinden was een foutje in 'Figuur 12. Scherm met daarop de s tartpagin a van de MijnOmgeving'.

2024-01-25 21:33 UTC, JeroenduC requested changes
Alleen nog even de tekst bij Figuur 12 fixen. Voor de rest helemaal prima, mooi!

2024-01-26 11:29 UTC, Yolijn commented on docs/onderzoek-bekijken/wmebv/vng-online-formulieren.md
> +    <figcaption>Figuur 12. Scherm met daarop de startpagina van de MijnOmgeving</figcaption>
@JeroenduC Volgens mij staat deze nu veel mooier ;)

2024-01-26 11:41 UTC, JeroenduC commented on docs/onderzoek-bekijken/wmebv/vng-online-formulieren.md
> +    <figcaption>Figuur 12. Scherm met daarop de startpagina van de MijnOmgeving</figcaption>
Super!

2024-01-26 11:42 UTC, JeroenduC approved these changes
Top! Wat mij betreft helemaal in orde.

2024-01-26 12:35 UTC, merged